### ISSUE TITLE
Helloworld in http://gubaer.github.io/josm-scripting-plugin/doc/scripting-environment.html

### ISSUE THREAD

**Issue by bjohas** [Gubaer/josm-scripting-plugin#43] opened 2017-05-24 12:47 UTC
The documentation http://gubaer.github.io/josm-scripting-plugin/doc/scripting-environment.html says 

> The places, where the Scripting Plugin is looking for modules, can be configured in the preferences. It looks for modules in two places:
> ...
> Then, it tries to load it from one of the configured plugin repositories. Each repository is either a directory in the local file system or in jar/zip file in the local filesystem.

However, we cannot get the helloworld example to work - we've added the directory with file:// to the JOSM plugin repositories, but get an error. Any ideas what could be wrong?

Many thanks!

**Comment by Gubaer** [comment] 2017-05-24 14:32
I'll have a look into it tomorrow, will keep you posted

**Comment by bjohas** [comment] 2017-05-24 15:19
@Gubaer, many thanks, that's amazing!

Just to provide some more information. This is on OS X, latest stable of JOSM, where under plugin sources I have added:

file:///Users/.../lib

In lib, I have

```// file: helloworld.js
(function() {
exports.sayHello = function() {
    console.println("Hello world!");
};
}());
```

(amended from the example) and then in the scripting console

```var hello = require("helloworld");
hello.sayHello();
```

It comes back with an error. 

Thanks - and looking forward to hearing more!

**Comment by Gubaer** [comment] 2017-05-25 13:14
Unfortunately, I can't reproduce. On my Ubuntu box it works as expected. I don't have access to a computer running OS X.

I had to add a `require("josm/scriptingconsole")` to your sample script, though. 

```javascript
// file: helloworld.js
(function() {
var console = require("josm/scriptingconsole");
exports.sayHello = function() {
    console.println("Hello world!");
};
}());
```
What if you require this version? Do you still get an error?  Do you see any error message or stack trace in the text, JOSM writes to stdout?

**Comment by bjohas** [comment] 2017-05-25 13:37
I've tried that addition, but I still get the script error popup, saying "An error occurred in the script". It doesn't cause a JOSM error. I'm not sure how to launch JOSM so that errors are logged to the terminal. 

How are your plugin directories set up? As I described above?

(Btw. we had the same error trying on windows.)

**Comment by Gubaer** [comment] 2017-05-25 16:31
Yes, as you described, except that I use an absolute path `/foo/bar/`, not a relative path `/Users/.../lib`.

On my Windows 10 system it works too. There I launch JOSM with the following PowerShell script

```PowerShell
# josm.ps1
$josm_home="d:\full\path\to\josmhome"
java "-Djosm.home=${josm_home}" -classpath "josm-tested.jar;jython-standalone-2.5.3.jar" org.openstreetmap.josm.gui.MainApplication
```
This will launch both JOSM and a PowerShell-Terminal where error messages and stack traces are logged.

**Comment by bjohas** [comment] 2017-05-25 16:31
Just wondering - should require.paths return anything? E.g.

```
var console = require("josm/scriptingconsole");
console.println(" paths = "+require.paths );
```
?

**Comment by Gubaer** [comment] 2017-05-25 16:34
Good question, I don't know, will have to check

**Comment by bjohas** [comment] 2017-05-25 17:08
OK, I've got this partially figured out. Adding the plugins directory didn't work, but adding the helloworld.js here 

~/Library/JOSM/plugins/scripting/modules

did work. See https://josm.openstreetmap.de/wiki/Help/Preferences/Plugins, https://josm.openstreetmap.de/wiki/Help/Preferences#Defaultlocation. I'll write this up, and add the link here shortly.

**Comment by bjohas** [comment] 2017-05-25 17:21
Btw. I didn't quite manage to launch JOSM as you described, but have asked a question here: https://help.openstreetmap.org/questions/56316/josm-with-error-console.

**Comment by bjohas** [comment] 2017-05-25 17:51
Follow-up question: In the helloworld example, it seems that if I change the helloworld.js file in the plugins directory), the main script (in scripting console) doesn't notice. I.e. if I keep running the same same main script, but change the helloworld.js script, the results don't change. So somehow helloworld.js is cached. Is there a way to disable that?

**Comment by Gubaer** [comment] 2017-05-26 06:34
No, unfortunaltely not. I'm not aware of such a possibility. If you somewhere find a switch or option to disable it, I'd abe interested to use it in the plugin! Please let me know.

**Comment by bjohas** [comment] 2017-05-26 09:08
Right - we got to the bottom of this! The directories need to be added to the Rhino engine tab in the scripting plugin preferences, not to the sources in the general plugin preferences! There is a broken image on this page  http://gubaer.github.io/josm-scripting-plugin/doc/scripting-environment.html that would probably show this. Sorry for the confusion, and many thanks!

About the caching - I'll investigate that and will get back to you!

**Comment by Gubaer** [comment] 2017-05-26 09:23
> The directories need to be added to the Rhino engine tab in the scripting plugin preferences, not to the sources in the general plugin preferences! There is a broken image on this page http://gubaer.github.io/josm-scripting-plugin/doc/scripting-environment.html that would probably show this.
Yes, exactly, it should show this! I'll fix the documentation.

**Comment by bjohas** [comment] 2017-05-26 09:52
Excellent, thanks! I've written this up here http://bjohas.de/wiki/Maps/JOSM/scripting_plugin. We're putting some scripts that we're developing here https://github.com/OSM-Utilities/JOSM-Scripts-HOT - nothing much there yet though. Thanks for your help!

**Comment by Gubaer** [comment] 2017-05-26 17:17
Thanks for the writeup! I've [fixed](http://gubaer.github.io/josm-scripting-plugin/doc/scripting-environment.html) the broken link.

Closing this issue.

**Closed by Gubaer** 2017-05-26 17:17 UTC
Labels: problem

**Comment by bjohas** [comment] 2017-05-26 17:25
Thanks! Good to have the image. I've posted to the JOSM dev list about the caching issue as well.

**Comment by gyslerc** [comment] 2017-06-06 03:47
Hi I am working on a script for JOSM-Scripts-HOT. 
I would like to create a button, when clicked, it will create a form which will take in user inputs and pass it to a function. I would like your input on the best way to proceed. 

For the first part of creating a button per instruction in -http://gubaer.github.io/josm-scripting-plugin/apidoc/mixins/JSActionMixin.html. 
My question is, how can I verify that a button is added so it will not be added again. 
In addToMenu, the code example should be call .addToMenu not just addTo. 
var JSAction = require("josm/ui/menu").JSAction;
// adds a new action to the JOSM edit menu
new JSAction({name: "My Action"})
   .addToMenu(josm.menu.get("edit"));

The second part is to get user inputs. One option is to use alerts as described at this link: (http://gubaer.github.io/josm-scripting-plugin/apidoc/namespaces/josm.html#alert). 
I am writing in js, how can I add JOptionPane as done in the python code ( from javax.swing import JOptionPane)? 
Thank you!

**Comment by Gubaer** [comment] 2017-06-06 05:42
I'll have a look into it, but probably not before thursday

**Comment by bjohas** [comment] 2017-06-21 11:29
@Gubaer - about the caching. I guess the caching happens because the object persists in JOSM, even once it has run, i.e. objects are not destroyed when the script finished. Do you have any ideas how the objects could be deleted? ("delete obj" doesn't seem to work.)

**Comment by Gubaer** [comment] 2017-07-12 09:42
I'm not sure which object you are referring to. What do you mean with "object"? The loaded script? A JavaScript object you create with `new` in the script? Do you have a code snippet which shows which object you are referring to?
