### ISSUE TITLE
Can't install on JOSM 18323

### ISSUE THREAD

**Issue by pl71** [Gubaer/josm-scripting-plugin#92] opened 2021-11-27 07:17 UTC
I can't install on JOSM 18323;
Class org.openstreetmap.josm.plugins.scripting.ScriptingPlugin not found.

**Comment by Gubaer** [comment] 2021-12-05 11:09
I can't reproduce this. On my ubuntu box it works with JOSM 18327. Can you be more specific? What's your OS? What are your steps before you see this message?

**Comment by pl71** [comment] 2022-01-28 20:28
Windows. But now plugin installs normally. JOSM 18360

**Comment by Gubaer** [comment] 2022-01-29 17:29
Ok, great news! Closing the issue.

**Closed by Gubaer** 2022-01-29 17:29 UTC
